# Generated by Django 6.0.4 on 2026-05-02 19:19

import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=questions.models.avatar_upload_path, verbose_name='Аватар'),
        ),
    ]
